# Generated by Django 4.1.2 on 2022-10-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="medal",
            field=models.CharField(
                blank=True,
                choices=[("GOLD", "Gold"), ("SILVER", "Silver"), ("BRONZE", "Bronze")],
                max_length=10,
            ),
        ),
    ]
