# Generated by Django 4.1.2 on 2022-10-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_person_medal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-age"],
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AlterModelTable(
            name="person",
            table="person",
        ),
    ]
