# Generated by Django 4.1.2 on 2022-10-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_author_blog_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("data", models.JSONField(null=True)),
            ],
            options={
                "db_table": "dog",
                "ordering": ["name"],
            },
        ),
    ]
